languages = {
    "pt": {
        "help_title": "📘 Lista de Comandos",
        "help_desc": "Aqui estão todos os comandos que você pode usar:",
        "cmd_start": "Cria seu pet inicial. (My!start)",
        "cmd_status": "Mostra o status atual do seu pet. (My!status)",
        "cmd_feed": "Alimenta seu pet. (My!feed)",
        "cmd_play": "Brinca com seu pet. (My!play)",
        "cmd_bath": "Dá banho no seu pet. (My!bath)",
        "cmd_sleep": "Coloca o pet para dormir. (My!sleep)",
        "cmd_lang": "Troca o idioma do bot. (My!lang pt/en)",
        "need_start": "Você ainda não tem um pet. Use `My!start` para escolher um.",
        "fed_pet": "foi alimentado e está mais satisfeito!",
        "played_pet": "brincou e está mais feliz!",
        "bath_pet": "tomou um banho e está limpinho!",
        "sleep_pet": "descansou e recuperou toda a energia!",
        "already_has_pet": "Você já tem um pet registrado!",
        "choose_invalid": "Escolha inválida.",
        "ask_nickname": "Agora escolha um apelido para seu pet:",
        "registered": "🎉 Seu pet **{nickname}** ({pet}) foi registrado com sucesso!",
        "gender_male": "macho",
        "gender_female": "fêmea",
        "gender_neutral": "andrógeno",
        "lang_set_pt": "Idioma alterado para **Português**!",
        "lang_set_en": "Language changed to **English**!"
    },

    "en": {
        "help_title": "📘 Command List",
        "help_desc": "Here are all the commands you can use:",
        "cmd_start": "Creates your starter pet. (My!start)",
        "cmd_status": "Shows your pet's current status. (My!status)",
        "cmd_feed": "Feeds your pet. (My!feed)",
        "cmd_play": "Plays with your pet. (My!play)",
        "cmd_bath": "Gives your pet a bath. (My!bath)",
        "cmd_sleep": "Lets your pet sleep. (My!sleep)",
        "cmd_lang": "Changes bot language. (My!lang pt/en)",
        "need_start": "You don't have a pet yet. Use `My!start` to choose one.",
        "fed_pet": "has been fed and is more satisfied!",
        "played_pet": "played and is happier now!",
        "bath_pet": "had a bath and is clean now!",
        "sleep_pet": "slept and restored all energy!",
        "already_has_pet": "You already have a registered pet!",
        "choose_invalid": "Invalid choice.",
        "ask_nickname": "Now choose a nickname for your pet:",
        "registered": "🎉 Your pet **{nickname}** ({pet}) has been registered!",
        "gender_male": "male",
        "gender_female": "female",
        "gender_neutral": "androgynous",
        "lang_set_pt": "Idioma alterado para **Português**!",
        "lang_set_en": "Language changed to **English**!"
    }
}